version: '3.1'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - adminerData:/var/log/adminer
  es01:
    image: bitnami/elasticsearch:8.9.2
    container_name: es01
    restart: always
    volumes:
      - elasticData:/bitnami/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=${CLUSTER_NAME}
    networks:
      - elastic

  kibana:
    depends_on:
      - es01
    image: bitnami/kibana:8.9.2
    volumes:
      - kibanadata:/bitnami/kibana
    ports:
      - 5601:5601
    environment:
      - KIBANA_ELASTICSEARCH_URL=http://es01:9200
    networks:
      - elastic

volumes:
  adminerData: 
    driver: local
  kibanadata:
    driver: local
  elasticData:
    driver: local

networks:
  elastic:
    driver: bridge